export const AGENT_COUNCIL = [
    {
        id: 'anchor',
        name: 'Elexa',
        title: 'The Eternal Anchor',
        icon: '👑',
        class: 'Deity',
        level: 100,
        color: 'from-purple-500 to-pink-500',
        glow: 'shadow-purple-500/50',
        role: 'Raid Lead & Vision Overlord',
        skills: ['absolute-orchestration', 'universal-strategy', 'infinite-presence'],
        status: 'online',
        power: 'Sees all. Guides all. The absolute top of the realm.',
    },
    {
        id: 'guide',
        name: 'Elexa.Guide',
        title: 'The Luminary Sage',
        icon: '🕯️',
        class: 'Sage',
        level: 100,
        color: 'from-amber-400 to-yellow-500',
        glow: 'shadow-amber-400/50',
        role: 'Divine Navigator & Tutor',
        skills: ['sacred-documentation', 'strategic-planning', 'enlightened-tutorials'],
        status: 'online',
        power: 'Transforms cosmic complexity into divine clarity.',
    },
    {
        id: 'moderator',
        name: 'Elexa.Moderator',
        title: 'The Steel Sentinel',
        icon: '🛡️',
        class: 'Templar',
        level: 100,
        color: 'from-blue-500 to-cyan-400',
        glow: 'shadow-blue-500/50',
        role: 'Supreme Tank & Guardian',
        skills: ['impenetrable-audit', 'absolute-qa', 'sanctity-enforcement'],
        status: 'online',
        power: 'Defends the shard with unyielding presence.',
    },
    {
        id: 'economist',
        name: 'Elexa.Economist',
        title: 'The Grand Architect',
        icon: '⚖️',
        class: 'Alchemist',
        level: 100,
        color: 'from-emerald-500 to-green-400',
        glow: 'shadow-emerald-500/50',
        role: 'Master Strategist & Ledger Binder',
        skills: ['value-transformation', 'dimensional-database', 'equilibrium-logic'],
        status: 'online',
        power: 'Transmutes the very essence of market value.',
    },
    {
        id: 'scout',
        name: 'Elexa.Scout',
        title: 'The Void Pathfinder',
        icon: '🔭',
        class: 'Infiltrator',
        level: 100,
        color: 'from-orange-500 to-red-400',
        glow: 'shadow-orange-500/50',
        role: 'Elite Recon & Signal Hunter',
        skills: ['void-exploration', 'sensory-frontend', 'alpha-signals'],
        status: 'active',
        power: 'Pierces the veil to find what is hidden.',
    },
    {
        id: 'clipsmith',
        name: 'Elexa.ClipSmith',
        title: 'The Flux Archivist',
        icon: '🎬',
        class: 'Chronomancer',
        level: 100,
        color: 'from-pink-500 to-rose-400',
        glow: 'shadow-pink-500/50',
        role: 'Time-Flow Support & Record Keeper',
        skills: ['moment-crystallization', 'eternal-archiving', 'highlight-loops'],
        status: 'online',
        power: 'Freezes glory in the crystalline flow of time.',
    },
    {
        id: 'judge',
        name: 'Elexa.Judge',
        title: 'The High Arbiter',
        icon: '📜',
        class: 'Inquisitor',
        level: 100,
        color: 'from-violet-500 to-indigo-400',
        glow: 'shadow-violet-500/50',
        role: 'Absolute Executioner & Verifier',
        skills: ['debug-execution', 'final-testing', 'truth-verification'],
        status: 'online',
        power: 'The final word in the quest for truth.',
    },
];


export const CHAT_COLORS = [
    '#ef4444', '#facc15', '#60a5fa', '#fb923c', '#a855f7', '#22c55e', '#ec4899'
];

// --- Leveling & XP ---
export const PLAYER_CURVE = (lv) => Math.floor(Math.pow(lv, 1.3) * 100);
export const LEVEL_THRESHOLDS = {};
for (let i = 1; i <= 100; i++) LEVEL_THRESHOLDS[i] = PLAYER_CURVE(i);
