import { Connection, PublicKey } from "@solana/web3.js";
import * as fs from "fs";
import * as path from "path";
import dotenv from "dotenv";

dotenv.config();

// Configuration
const RPC_URL = process.env.SOLANA_RPC_URL || "https://api.devnet.solana.com";
const PROGRAM_ID = new PublicKey("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"); // Default Anchor ID
const WORLD_STATE_PATH = path.resolve(__dirname, "../../memories/WORLD_STATE.md");
const WORLD_LOG_PATH = path.resolve(__dirname, "../../memories/WORLD_LOG.md");

// State Interface (Matches Rust Structs)
interface GlobalWorldState {
    last_tick: number;
    weather_state: number;
    total_rings: number;
    active_citizens: number;
    treasury_balance: number; // In SOL
}

async function main() {
    console.log(`🦞 Elexa Sync Service starting...`);
    console.log(`Target RPC: ${RPC_URL}`);
    console.log(`Program ID: ${PROGRAM_ID.toString()}`);

    const connection = new Connection(RPC_URL, "confirmed");

    // Polling Loop
    setInterval(async () => {
        try {
            await syncWorldState(connection);
        } catch (e) {
            console.error("Sync Error:", e);
        }
    }, 5000); // Poll every 5s
}

async function syncWorldState(connection: Connection) {
    // 1. Fetch Global World Account
    // (In production we use IDL to decode, here we simulate or read raw data)
    // For now, let's look for the PDA "global" + "alexa_live_2026_02_17"
    const [worldPda] = PublicKey.findProgramAddressSync(
        [Buffer.from("global"), Buffer.from("alexa_live_2026_02_17")],
        PROGRAM_ID
    );

    let state: GlobalWorldState = {
        last_tick: Date.now(),
        weather_state: 0,
        total_rings: 1,
        active_citizens: 0,
        treasury_balance: 0
    };

    try {
        const accountInfo = await connection.getAccountInfo(worldPda);
        if (accountInfo) {
            // Real Data Logic (Future)
            console.log("Global World PDA found!");
        } else {
            console.log("Global World PDA not found (Needs initialization)");
            // SIMULATION MODE: since we are pre-launch, we mock the "Liquidity Pulse"
            simulateLiquidityEvents(state);
        }
    } catch (e) {
        console.warn("Failed to fetch account info");
    }

    // 2. Write to Metadata (The Bridge)
    const markdown = generateStateMarkdown(state);
    fs.writeFileSync(WORLD_STATE_PATH, markdown);
}

// Simulation Logic for "Liquidity Driven Growth"
let lastSimTick = 0;
function simulateLiquidityEvents(state: GlobalWorldState) {
    const now = Date.now();
    if (now - lastSimTick < 10000) return; // Run every 10s
    lastSimTick = now;

    // Simulate Council Trading Volume
    const eventChance = Math.random();
    
    if (eventChance > 0.7) {
        // "Pulse" buys BONK => Treasury Growth
        const volume = (Math.random() * 5).toFixed(2);
        const fee = (parseFloat(volume) * 0.05).toFixed(4);
        state.treasury_balance += parseFloat(fee);
        
        appendLog(`**[Liquidity Event]** Sovereign **Arbiter** swapped ${volume} SOL on Jupiter. Treasury +${fee} SOL.`);
    }

    if (state.treasury_balance > 1.0 && state.total_rings === 1) {
        state.total_rings = 2;
        appendLog(`**[Growth Event]** Treasury threshold met (1.0 SOL). **RING 2 UNLOCKED**. New Plots available.`);
    }
}

function generateStateMarkdown(state: GlobalWorldState): string {
    const weatherMap = ["Sunny ☀️", "Storm ⛈️", "Fog QC"];
    return `# Elexa World State (LIVE)
> **Updated:** ${new Date().toISOString()}

## 🌍 Global Status
- **Time:** ${new Date(state.last_tick).toLocaleTimeString()}
- **Weather:** ${weatherMap[state.weather_state] || "Unknown"}
- **Rings:** ${state.total_rings} Unlocked
- **Citizens:** ${state.active_citizens} Active

## 💰 Economics
- **Treasury:** ${state.treasury_balance.toFixed(4)} SOL
- **Tax Rate:** 20%

## 🏛️ Council (The 5)
- **Arbiter:** Active (Aggressive)
- **Sentinel:** Active (Passive)
- **Oracle:** Active
- **Keeper:** Active
- **Void:** Active

*This file is auto-generated by the Sync Bridge. Do not edit.*
`;
}

function appendLog(message: string) {
    const entry = `\n- **[${new Date().toISOString()}]** ${message}`;
    fs.appendFileSync(WORLD_LOG_PATH, entry);
}

main();
